
import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import { format } from 'date-fns';

const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 30,
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 2,
        borderBottomColor: '#112143',
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#112143',
    },
    subtitle: {
        fontSize: 12,
        color: '#666666',
        marginTop: 5,
    },
    section: {
        margin: 10,
        padding: 10,
        flexGrow: 1,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 5,
    },
    label: {
        fontSize: 12,
        color: '#666666',
    },
    value: {
        fontSize: 12,
        color: '#000000',
        fontWeight: 'bold',
    },
    total: {
        marginTop: 20,
        borderTopWidth: 1,
        borderTopColor: '#EEEEEE',
        paddingTop: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    totalLabel: {
        fontSize: 14,
        fontWeight: 'bold',
    },
    totalValue: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#006400',
    },
    footer: {
        marginTop: 50,
        textAlign: 'center',
        fontSize: 10,
        color: '#999999',
    }
});

interface ReceiptProps {
    receiptNumber: string;
    date: Date;
    tenantName: string;
    propertyName: string;
    amount: number;
    paymentMethod: string;
}

export const ReceiptPDF = ({ receiptNumber, date, tenantName, propertyName, amount, paymentMethod }: ReceiptProps) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>Payment Receipt</Text>
                <Text style={styles.subtitle}>PropTraka Management</Text>
            </View>

            <View style={styles.section}>
                <View style={styles.row}>
                    <Text style={styles.label}>Receipt No:</Text>
                    <Text style={styles.value}>{receiptNumber}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Date:</Text>
                    <Text style={styles.value}>{format(date, 'dd MMM yyyy HH:mm')}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Tenant:</Text>
                    <Text style={styles.value}>{tenantName}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Property:</Text>
                    <Text style={styles.value}>{propertyName}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Paid Via:</Text>
                    <Text style={styles.value}>{paymentMethod}</Text>
                </View>

                <View style={styles.total}>
                    <Text style={styles.totalLabel}>Total Amount Paid:</Text>
                    <Text style={styles.totalValue}>KES {amount.toLocaleString()}</Text>
                </View>
            </View>

            <View style={styles.footer}>
                <Text>Thank you for your payment.</Text>
                <Text>Generated by PropTraka AI</Text>
            </View>
        </Page>
    </Document>
);
